# Site settings
title: GVSU Computing Club Game Jam
email: frederer@gvsu.edu
url: https://https://gvsu-gamejam.github.io/freelancer-theme
current_prompt: collect
2025_prompt: collect
description: "Resource site for game jams hosted by the GVSU Computing Club."
keywords: "computing club, university, game jam, game jams, video games, video game development, club activities"
# skills: "Web Developer - Graphic Artist - User Experience Designer"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: GVSU Computing Club
  location: Grand Valley State University
  social: Around the Web
  credits: Credits
  url: https://www.gvsu.edu/computing/student-organizations-22

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: discord
    url: https://discord.gg/KDPKWG5x
  - title: linkedin
    url: https://www.linkedin.com/company/computing-club
  - title: instagram
    url: https://www.instagram.com/gvsucomputingclub/
  - title: github
    url: https://github.com/GVSU-Computing-Club
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  # - line: 3481 Melrose Place
  - line: Allendale, MI, USA

# Credits content
credits: '<a href="https://github.com/jeromelachaud/freelancer-theme" target="_blank">site template</a><br />site maintained by <a href="https://efredericks.github.io" target="_blank">fredericks</a>'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
